#ifndef CGRASCHEDULER_CGRAARCHDEFS_H
#define CGRASCHEDULER_CGRAARCHDEFS_H

#define CONTROL_PORT_OUT_A 0
#define CONTROL_PORT_OUT_B 1

#define CONTROL_RF_OUT 2
#define CONTROL_FIFO_OUT 3

#define CONTROL_PORT_IN_A 0
#define CONTROL_FIFO_IN 1

#define CONTROL_PORT_IN_B 0
#define CONTROL_RF_IN 1

#define PORT_A 0
#define PORT_B 1
#define PORT_BRANCH 2

#endif //CGRASCHEDULER_CGRAARCHDEFS_H
