//
// Created by lucas on 30/01/19.
//

#ifndef MAIN_SCHEDULER_DEFS_H
#define MAIN_SCHEDULER_DEFS_H

#define SCHEDULE_SUCCESS -1
#define SCHEDULE_HAS_LOOPED -2
#define SCHEDULE_PE_FREE_IS_GONE -3
#define SCHEDULER_INSUFFICIENT_PE_IN -4
#define SCHEDULER_INSUFFICIENT_PE_OUT -5
#define SCHEDULER_INSUFFICIENT_PE -6



#endif //MAIN_SCHEDULER_DEFS_H
