##############################################################
#                                                            #
# Xeon(R) + FPGA AFU Simulation Environment                  #
# File generated by ase/scripts/generate_ase_environment.py  #
#                                                            #
##############################################################

SIMULATOR ?= VCS

DUT_VLOG_SRC_LIST = /home/lucas/Documentos/acc-management-repo/samples/loopback/hw/sim/afu_sim/vlog_files.list 

ASE_PLATFORM ?= FPGA_PLATFORM_INTG_XEON

