//
// Generated by afu_json_mgr from /home/lucas/Documentos/acc-management-repo/hw/static/afu.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "acc_management"
`define AFU_ACCEL_UUID 128'h9f81ba12_1d38_4cc7_953a_dafeef45065b
`define AFU_IMAGE_INTERFACE_UUID "00000000-0000-0000-0000-000000000000"
`define AFU_IMAGE_MAGIC_NO 488605312
`define AFU_IMAGE_POWER 0

`endif // __AFU_JSON_INFO__
