#!/bin/bash

rm -rf afu_synth
python3 $FDAM_BASEDIR/fdam-hw-generator/src/update_sources.py
afu_synth_setup  -s sources.txt --lib $SR_503_RELEASE_DIR/hw/lib afu_synth

echo "#!/bin/sh" > afu_synth/clean.sh
echo "" >> afu_synth/clean.sh
echo  "bash $SR_503_RELEASE_DIR/bin/clean.sh" >> afu_synth/clean.sh
echo "#!/bin/sh" > afu_synth/run.sh
echo "" >> afu_synth/run.sh
echo "datainicial=\`date +%s\`" >> afu_synth/run.sh
echo  "bash $SR_503_RELEASE_DIR/bin/run.sh -o `pwd`/fdam_afu.gbs" >> afu_synth/run.sh
echo "datafinal=\`date +%s\`" >> afu_synth/run.sh
echo "diff=\`expr \$datafinal - \$datainicial\`" >> afu_synth/run.sh
echo "resultado=\`expr 10800 + \$diff\`" >> afu_synth/run.sh
echo "time=\`date -d @\$resultado +%H:%M:%S\`" >> afu_synth/run.sh
echo "echo \"Total Time spend: \$time \" >> time_spend.txt" >> afu_synth/run.sh
echo "echo \"Total Time spend: \$time \"" >> afu_synth/run.sh

chmod +x afu_synth/clean.sh
chmod +x afu_synth/build/generate_pr_bitstream.sh
chmod +x afu_synth/run.sh

